name: Build Images

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 22 * * *'

jobs:
  rundeck:
    name: Build Rundeck Images

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |-
          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - name: Run Crossbuild
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t "homelabs/rundeck:latest" \
            -t "homelabs/rundeck:$(date '+%Y%m%d%H%M')" --push .
